---
- hosts: ec2_bastion
  remote_user: ec2-user
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: False
  tasks:
    - name: copy Pem file
      copy:
        src: new_apple_key.pem
        dest: ~/new_apple_key.pem
        mode: 0400
    - name: import private Ip
      include_vars: vars/vpc_ids
    - name: adding IPs into host file
      blockinfile:
        path: /etc/hosts
        marker: "## private IP Baastion"
        block: |
          web01 {{ web01_ip }}
          app01 {{ app01_ip }}
          mc01 {{ mc01_ip }}
          rmq01 {{ rmq01_ip }}
          db01 {{ db01_ip }}

