---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc vars
      include_vars: vars/vpc_setup

    - name: create a VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Create subnet Pub1
      ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSubCidr1 }}"
        az: "{{ zone1 }}"
        map_public: yes
        tags:
          Name: "Vp-Pub-sub-1"
      register: pub_sub1
    - name: Create subnet Pub2
      ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSubCidr2 }}"
        az: "{{ zone2 }}"
        map_public: yes
        tags:
          Name: "Vp-Pub-sub-2"
      register: pub_sub2
    - name: Create subnet Pub3
      ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSubCidr3 }}"
        az: "{{ zone3 }}"
        map_public: yes
        tags:
          Name: "Vp-Pub-sub-3"
      register: pub_sub3

    - name: Create subnet Private 1
      ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSubCidr1 }}"
        az: "{{ zone1 }}"
        tags:
          Name: "Vp-Priv-sub-1"
      register: priv_sub1
    - name: Create subnet Private 2
      ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSubCidr2 }}"
        az: "{{ zone2 }}"
        tags:
          Name: "Vp-Priv-sub-2"
      register: priv_sub2
    - name: Create subnet Private 3
      ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSubCidr3 }}"
        az: "{{ zone3 }}"
        tags:
          Name: "Vp-Priv-sub-3"
      register: priv_sub3
    
    - name: Create Internet gateway with tags
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        tags:
            Name: Vprofile_igw
            Maintener: Devops
      register: igw_out
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: "Public Vprofile"
        subnets:
          - "{{ pub_sub1.subnet.id }}"
          - "{{ pub_sub2.subnet.id }}"
          - "{{ pub_sub3.subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: pub_rt_out

    - name: Create new nat gateway with client token.
      ec2_vpc_nat_gateway:
        state: "{{ state }}"
        subnet_id: "{{ priv_sub1.subnet.id }}"
        wait: yes
        region: "{{ region }}"
        if_exist_do_not_create: yes
      register: nat_gw_out
    - name: Set up private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: "Private Vprofile"
        subnets:
          - "{{ priv_sub1.subnet.id }}"
          - "{{ priv_sub2.subnet.id }}"
          - "{{ priv_sub3.subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat_gw_out.nat_gateway_id }}"
      register: priv_rt_out
    
    - name: Create variabel file
      copy:
        content: "vpcid: {{ vpcout.vpc.id }}\npubsub1: {{ pub_sub1.subnet.id }}\npubsub2: {{ pub_sub2.subnet.id }}\npubsub3: {{ pub_sub3.subnet.id }}\nprivsub1: {{ priv_sub1.subnet.id }}\nprivsub2: {{ priv_sub2.subnet.id }}\nprivsub3: {{ priv_sub3.subnet.id }}\nigw: {{ igw_out.gateway_id }}\npubrtid: {{ pub_rt_out.route_table.id }}\nnatgwid: {{ nat_gw_out.nat_gateway_id }}\nprivrtid: {{ priv_rt_out.route_table.id }}"
        dest: vars/vpc_ids